# version: "3.9"

# services:
#   jekyll:
#     build: .
#     container_name: jekyll-site
#     ports:
#       - "4000:4000"
#     volumes:
#       - .:/app
#       - bundle_cache:/usr/local/bundle
#     command: bundle exec jekyll serve --host 0.0.0.0 --port 4000 --watch --force_polling

# volumes:
#   bundle_cache:

services:
  jekyll:
    image: jekyll/jekyll:latest   # ganti jadi latest / pages
    container_name: jekyll_site
    command: jekyll serve --watch --force_polling --host 0.0.0.0 --port 4000 --livereload
    # command: jekyll serve --watch --force_polling --host 0.0.0.0 --port 4000 --livereload --config _config.yml,_config.dev.yml
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - jekyll_bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development

volumes:
  jekyll_bundle:
